"""A bundled bank of trivia for calibration practice.

Two flavours, matching the two classic calibration exercises:

* ``NUMERIC`` -- questions with a single numeric answer. Used for the
  "90% confidence interval" drill (Hubbard, *How to Measure Anything*): give a
  range you're 90% sure contains the truth; a well-calibrated person captures
  the answer in ~90% of their ranges.
* ``BINARY`` -- true/false statements. Used for the confidence drill: say
  whether it's true and how sure you are (50-100%); scored with the Brier score.

Every fact here is meant to be stable and checkable. Each item carries an
optional ``source`` note. The set is intentionally general-knowledge and
Western-biased-neutral where possible; it is a practice aid, not a pub quiz.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class NumericQuestion:
    prompt: str
    answer: float
    unit: str = ""
    source: str = ""


@dataclass(frozen=True)
class BinaryQuestion:
    prompt: str
    answer: bool
    source: str = ""


NUMERIC: list[NumericQuestion] = [
    NumericQuestion("In what year was the Eiffel Tower completed?", 1889, ""),
    NumericQuestion("How long is the river Nile, to the nearest 100 km?", 6650, "km"),
    NumericQuestion("How many bones are in the adult human body?", 206, ""),
    NumericQuestion("In what year did Apollo 11 land humans on the Moon?", 1969, ""),
    NumericQuestion("How many member states does the United Nations have (2024)?", 193, ""),
    NumericQuestion("What is the height of Mount Everest above sea level?", 8849, "m"),
    NumericQuestion("What is the average distance from the Earth to the Moon?", 384400, "km"),
    NumericQuestion("How many keys are on a standard piano?", 88, ""),
    NumericQuestion("In what year did the Berlin Wall fall?", 1989, ""),
    NumericQuestion("How many chemical elements are on the periodic table (2024)?", 118, ""),
    NumericQuestion("How many players from one team are on a soccer field at kickoff?", 11, ""),
    NumericQuestion("In what year was the first iPhone released?", 2007, ""),
    NumericQuestion("What is the speed of light in a vacuum, in km/s?", 299792, "km/s"),
    NumericQuestion("How many chromosomes are in a typical human body cell?", 46, ""),
    NumericQuestion("In what year did the Titanic sink?", 1912, ""),
    NumericQuestion("What is the atomic number of oxygen?", 8, ""),
    NumericQuestion("What is the length of a marathon, to the nearest 0.1 km?", 42.2, "km"),
    NumericQuestion("How many hearts does an octopus have?", 3, ""),
    NumericQuestion("What is the speed of sound in air at 20 C, to the nearest m/s?", 343, "m/s"),
    NumericQuestion("In what year did World War II end?", 1945, ""),
    NumericQuestion("How many natural moons does Mars have?", 2, ""),
    NumericQuestion("What is the height of the Burj Khalifa?", 828, "m"),
    NumericQuestion("How many cards are in a standard deck without jokers?", 52, ""),
    NumericQuestion("In what year were the first modern Olympic Games held in Athens?", 1896, ""),
    NumericQuestion("What is the length of an Olympic swimming pool?", 50, "m"),
    NumericQuestion("How many teeth does a typical adult human have, including wisdom teeth?", 32, ""),
    NumericQuestion("What is the average human body temperature in Celsius?", 37, "C"),
    NumericQuestion("In what year was the United States Declaration of Independence adopted?", 1776, ""),
    NumericQuestion("How many Great Lakes are there in North America?", 5, ""),
    NumericQuestion("What is the mean diameter of the Earth, to the nearest 10 km?", 12742, "km"),
    NumericQuestion("How many pairs of ribs does a typical human have?", 12, ""),
    NumericQuestion("What is the distance from the Earth to the Sun (1 AU), in millions of km?", 149.6, "million km"),
    NumericQuestion("How many strings does a standard violin have?", 4, ""),
    NumericQuestion("In what year did the Western Roman Empire traditionally fall?", 476, ""),
    NumericQuestion("How many days does the Moon take to orbit Earth (sidereal), to 1 decimal?", 27.3, "days"),
    NumericQuestion("In what year were euro banknotes and coins first introduced?", 2002, ""),
    NumericQuestion("What is the boiling point of water at sea level in Celsius?", 100, "C"),
    NumericQuestion("How many legs does an insect have?", 6, ""),
    NumericQuestion("What is the freezing point of water in Fahrenheit?", 32, "F"),
    NumericQuestion("Around what year did Gutenberg introduce his printing press in Europe?", 1440, ""),
    NumericQuestion("In what year was the Battle of Hastings fought?", 1066, "", "Wikipedia: Battle of Hastings (14 Oct 1066)"),
    NumericQuestion("In what year was Magna Carta sealed by King John?", 1215, "", "Britannica: Magna Carta (15 June 1215)"),
    NumericQuestion("In what year did Constantinople fall to the Ottomans?", 1453, "", "Britannica: Fall of Constantinople (29 May 1453)"),
    NumericQuestion("In what year did Columbus first reach the Americas?", 1492, "", "Wikipedia: Voyages of Christopher Columbus (12 Oct 1492)"),
    NumericQuestion("In what year did Martin Luther publish his Ninety-five Theses?", 1517, "", "Britannica: Ninety-five Theses (31 Oct 1517)"),
    NumericQuestion("In what year was the Spanish Armada defeated?", 1588, "", "Britannica: Spanish Armada (1588)"),
    NumericQuestion("In what year did the Mayflower reach Plymouth in the Americas?", 1620, "", "History.com: Mayflower anchored in Plymouth Harbor (18 Dec 1620)"),
    NumericQuestion("In what year was the Peace of Westphalia signed?", 1648, "", "Wikipedia: Peace of Westphalia (Oct 1648)"),
    NumericQuestion("In what year did the Great Fire of London occur?", 1666, "", "Wikipedia: Great Fire of London (2-5 Sept 1666)"),
    NumericQuestion("In what year did Edward Jenner perform his first smallpox vaccination?", 1796, "", "History.com / British Red Cross: Edward Jenner vaccinates James Phipps (14 May 1796)"),
    NumericQuestion("In what year did the storming of the Bastille take place?", 1789, "", "Britannica: Storming of the Bastille (14 July 1789)"),
    NumericQuestion("In what year was the Battle of Waterloo fought?", 1815, "", "Britannica: Battle of Waterloo (18 June 1815)"),
    NumericQuestion("In what year did the American Civil War begin?", 1861, "", "Britannica: Battle of Fort Sumter (12 April 1861)"),
    NumericQuestion("In what year did the Wright brothers make the first powered flight?", 1903, "", "NASA / Smithsonian: First powered flight at Kitty Hawk (17 Dec 1903)"),
    NumericQuestion("In what year did World War I begin?", 1914, "", "Britannica: World War I (28 July 1914)"),
    NumericQuestion("In what year did the Bolshevik October Revolution take place in Russia?", 1917, "", "Wikipedia: October Revolution (7 Nov / 25 Oct O.S. 1917)"),
    NumericQuestion("In what year was the Treaty of Versailles signed?", 1919, "", "Wikipedia: Treaty of Versailles (28 June 1919)"),
    NumericQuestion("In what year did Alexander Fleming discover penicillin?", 1928, "", "Britannica / History.com: Fleming discovers penicillin (Sept 1928)"),
    NumericQuestion("In what year did Alexander Graham Bell receive his U.S. telephone patent?", 1876, "", "History.com / LOC: Bell telephone patent No. 174,465 (7 March 1876)"),
    NumericQuestion("In what year was Sputnik 1, the first artificial satellite, launched?", 1957, "", "NASA / Britannica: Sputnik 1 (4 Oct 1957)"),
    NumericQuestion("In what year did Yuri Gagarin become the first human in space?", 1961, "", "NASA / Britannica: Yuri Gagarin, Vostok 1 (12 April 1961)"),
    NumericQuestion("In what year did Abraham Lincoln deliver the Gettysburg Address?", 1863, "", "Wikipedia: Gettysburg Address (19 Nov 1863)"),
    NumericQuestion("In what year did the American Revolutionary War begin at Lexington and Concord?", 1775, "", "Britannica: Battles of Lexington and Concord (19 April 1775)"),
    NumericQuestion("In what year was the Roman Colosseum completed and opened?", 80, "", "Wikipedia / History.com: Colosseum completed and opened under Titus (AD 80)"),
    NumericQuestion("How many full years did Queen Victoria reign (1837 to 1901)?", 63, "years", "Wikipedia: Queen Victoria (reigned 63 years, 216 days)"),
    NumericQuestion("What is the maximum depth of Lake Baikal?", 1642, "m", "Wikipedia: Lake Baikal; Britannica"),
    NumericQuestion("What is the height of Mount Kilimanjaro above sea level?", 5895, "m", "Wikipedia: Mount Kilimanjaro; Nat Geo"),
    NumericQuestion("What is the height of K2, the world's second-highest mountain?", 8611, "m", "Wikipedia: K2; Britannica"),
    NumericQuestion("What is the summit elevation of Denali (per the 2015 survey)?", 6190, "m", "USGS/NPS Denali summit survey 2015 (20,310 ft)"),
    NumericQuestion("What is the height of Mount Fuji above sea level, to the nearest metre?", 3776, "m", "Wikipedia/Britannica: Mount Fuji (3,776.24 m)"),
    NumericQuestion("What is the height of Aconcagua, the highest peak in South America, to the nearest 100 m?", 7000, "m", "Wikipedia/Britannica: Aconcagua (6,959-6,967 m; all round to 7,000)"),
    NumericQuestion("What is the height of Mount Elbrus, the highest peak in Europe?", 5642, "m", "Wikipedia: Mount Elbrus; Britannica"),
    NumericQuestion("What is the height of Ben Nevis, the highest mountain in the British Isles?", 1345, "m", "Ordnance Survey 2016 remeasurement; Wikipedia: Ben Nevis"),
    NumericQuestion("What is the height of the Matterhorn?", 4478, "m", "Britannica: Matterhorn; myswitzerland.com"),
    NumericQuestion("What is the height of Mount Kosciuszko, the highest peak on mainland Australia?", 2228, "m", "Geoscience Australia; Wikipedia: Mount Kosciuszko"),
    NumericQuestion("What is the total height of Angel Falls, the world's tallest waterfall?", 979, "m", "Wikipedia: Angel Falls; Guinness World Records"),
    NumericQuestion("What is the height of Victoria Falls on the Zambezi River?", 108, "m", "Wikipedia: Victoria Falls; Britannica"),
    NumericQuestion("What is the approximate depth of the Challenger Deep in the Mariana Trench, to the nearest km?", 11, "km", "NOAA 2021 revised depth (10,935 m); Wikipedia: Challenger Deep"),
    NumericQuestion("What is the total area of Australia, to the nearest 100,000 square km?", 7700000, "km²", "Geoscience Australia (7,688,287 km²)"),
    NumericQuestion("What is the area of Greenland, the world's largest island, to the nearest 100,000 square km?", 2200000, "km²", "Britannica: Greenland (~2,166,000 km²); Wikipedia (2,175,600 km²)"),
    NumericQuestion("What is the area of the island country of Madagascar, to the nearest 10,000 square km?", 590000, "km²", "Wikipedia: Madagascar (587,040 km²)"),
    NumericQuestion("What is the surface area of Lake Superior, to the nearest 1,000 square km?", 82000, "km²", "Wikipedia/Britannica: Lake Superior (82,100 km²)"),
    NumericQuestion("How long is the Grand Canyon, to the nearest 10 km?", 450, "km", "NPS/Wikipedia: Grand Canyon (446 km / 277 mi)"),
    NumericQuestion("How long is the Great Barrier Reef, to the nearest 100 km?", 2300, "km", "Wikipedia: Great Barrier Reef; GBR Foundation (over 2,300 km)"),
    NumericQuestion("How long is the Suez Canal, to the nearest km?", 193, "km", "Wikipedia: Suez Canal (193.30 km)"),
    NumericQuestion("What is the surface elevation of Lake Titicaca?", 3812, "m", "Wikipedia: Lake Titicaca; NASA Earth Observatory"),
    NumericQuestion("How high does Uluru (Ayers Rock) rise above the surrounding plain?", 348, "m", "Parks Australia (uluru.gov.au); Britannica: Uluru"),
    NumericQuestion("How many African countries are members of the United Nations (as of 2024)?", 54, "", "UN Ask DAG FAQ; UN African Group membership"),
    NumericQuestion("What was the world population in mid-2024, to the nearest 0.1 billion?", 8.2, "billion", "UN World Population Prospects 2024 (8.2 billion in 2024)"),
    NumericQuestion("How many planets are in the Solar System?", 8, "", "NASA Science: About the Planets"),
    NumericQuestion("What is absolute zero in degrees Celsius, to the nearest whole degree?", -273, "°C", "Wikipedia: Absolute zero (-273.15 C)"),
    NumericQuestion("What is the atomic number of carbon?", 6, "", "Periodic table (RSC): carbon = 6"),
    NumericQuestion("What is the atomic number of gold?", 79, "", "Wikipedia: Gold (atomic number 79)"),
    NumericQuestion("How many chambers does the human heart have?", 4, "", "General anatomy references"),
    NumericQuestion("What is the pH of pure water at 25 °C?", 7, "", "US EPA / Chemistry LibreTexts: pure water pH ~7"),
    NumericQuestion("What is the acceleration due to gravity at Earth's surface, to 1 decimal place?", 9.8, "m/s²", "Standard gravity 9.80665 m/s²"),
    NumericQuestion("How many standard amino acids are encoded by the genetic code to build proteins?", 20, "", "Wikipedia: Proteinogenic amino acid (20 standard)"),
    NumericQuestion("What is the age of the universe in billions of years, to 1 decimal place?", 13.8, "billion years", "ESA Planck: 13.8 billion years"),
    NumericQuestion("How many pairs of cranial nerves does a human have?", 12, "", "Wikipedia: Cranial nerves (12 pairs)"),
    NumericQuestion("What percentage of Earth's surface is covered by water, to the nearest percent?", 71, "%", "USGS / NASA: ~71%"),
    NumericQuestion("What is the diameter of the Moon, to the nearest 100 km?", 3500, "km", "NASA Moon Fact Sheet (3475 km)"),
    NumericQuestion("What is the escape velocity from Earth's surface, to 1 decimal place?", 11.2, "km/s", "Wikipedia: Escape velocity (11.186 km/s)"),
    NumericQuestion("What is standard atmospheric pressure at sea level, to the nearest hectopascal?", 1013, "hPa", "Wikipedia: Atmospheric pressure (1013.25 hPa)"),
    NumericQuestion("Approximately how many neurons are in the human brain, in billions?", 86, "billion", "Herculano-Houzel 2009; Oxford Brain 2025 (~86 billion)"),
    NumericQuestion("What is the coefficient of Avogadro's number when written as X ×10²³ per mole, to 3 decimals?", 6.022, "×10²³ /mol", "SI: 6.02214076×10²³ /mol"),
    NumericQuestion("What is the effective (surface) temperature of the Sun's photosphere, to the nearest 100 K?", 5800, "K", "NASA Sun Fact Sheet (5772 K)"),
    NumericQuestion("How many Earth days does Mars take to orbit the Sun, to the nearest day?", 687, "days", "NASA Mars facts / Wikipedia (687 Earth days)"),
    NumericQuestion("How many bones are in one human hand?", 27, "", "TeachMeAnatomy: 8 carpals + 5 metacarpals + 14 phalanges = 27"),
    NumericQuestion("What is the acceleration due to gravity on the Moon's surface, to 1 decimal place?", 1.6, "m/s²", "Wikipedia: Gravitation of the Moon (1.62 m/s²)"),
    NumericQuestion("How many colours are traditionally listed in a rainbow (Newton's ROYGBIV)?", 7, "", "Newton's colour convention (ROYGBIV)"),
    NumericQuestion("What is the atomic number of iron?", 26, "", "Periodic table: iron = 26"),
    NumericQuestion("What is the freezing point of water in kelvin, to the nearest whole number?", 273, "K", "0 °C = 273.15 K"),
    NumericQuestion("What is the equatorial diameter of Jupiter, to the nearest 1000 km?", 143000, "km", "NASA Jupiter Fact Sheet (142,984 km)"),
    NumericQuestion("How many protons does a helium atom have?", 2, "", "Periodic table: helium atomic number 2"),
    NumericQuestion("In what year was Windows 95 released?", 1995, "", "Wikipedia: Windows 95 (retail release Aug 24, 1995); verified via Wikipedia and Microsoft Windows Insider Blog"),
    NumericQuestion("In what year did Apple introduce the original Macintosh?", 1984, "", "Wikipedia: Macintosh 128K (launched Jan 24, 1984); verified via Wikipedia and AppleInsider"),
    NumericQuestion("In what year was Wikipedia launched?", 2001, "", "Wikipedia: History of Wikipedia (launched Jan 15, 2001); verified via History.com and Britannica"),
    NumericQuestion("In what year was the transistor invented at Bell Labs?", 1947, "", "Computer History Museum: point-contact transistor, Dec 1947; verified via CHM and Britannica"),
    NumericQuestion("In what year did Alexander Graham Bell receive his patent for the telephone?", 1876, "", "US patent 174,465 issued March 7, 1876; verified via History.com and Smithsonian"),
    NumericQuestion("In what year was the arcade game Pac-Man first released?", 1980, "", "Wikipedia: Pac-Man (Japan, May 22, 1980); verified via Wikipedia and Museum of the Game"),
    NumericQuestion("In what year did Nintendo release the original Game Boy?", 1989, "", "Wikipedia: Game Boy (Japan April 21, 1989; NA July 31, 1989); verified via Wikipedia and PBS"),
    NumericQuestion("In what year was the Ford Model T introduced?", 1908, "", "Ford corporate history / Wikipedia: first Model T built Aug 1908, production began Oct 1, 1908; verified via Wikipedia, Britannica, The Henry Ford"),
    NumericQuestion("How many symphonies did Beethoven complete?", 9, "", "BSO / Classic FM: Beethoven's nine completed symphonies (10th left as sketches); verified via BSO and Classical-Music.com"),
    NumericQuestion("How many sonnets were published in Shakespeare's 1609 quarto collection?", 154, "", "Wikipedia: Shakespeare's sonnets (154 in 1609 Thorpe quarto); verified via Wikipedia and Folger Shakespeare Documented"),
    NumericQuestion("How wide is the Mona Lisa painting, to the nearest cm?", 53, "cm", "Louvre / Wikipedia: Mona Lisa 77 x 53 cm; verified via multiple sources, all round to 53 cm"),
    NumericQuestion("In what year did Michelangelo complete the Sistine Chapel ceiling?", 1512, "", "Wikipedia: Sistine Chapel ceiling (completed Oct 31, 1512, unveiled Nov 1, 1512); verified via Wikipedia and History.com"),
    NumericQuestion("In what year was the first Harry Potter book published?", 1997, "", "Wikipedia: Harry Potter and the Philosopher's Stone (Bloomsbury, June 26, 1997); verified via Wikipedia and Sotheby's"),
    NumericQuestion("In what year did Vincent van Gogh paint The Starry Night?", 1889, "", "MoMA: The Starry Night, Saint-Remy, June 1889; verified via MoMA collection page and Wikipedia"),
    NumericQuestion("What is the diameter of a standard compact disc (CD)?", 120, "mm", "Wikipedia: Compact disc (120 mm standard); verified via Wikipedia and Britannica"),
    NumericQuestion("What is the width of a sheet of A4 paper?", 210, "mm", "ISO 216 / Wikipedia: A4 is 210 x 297 mm; verified via ISO 216 and Wikipedia"),
    NumericQuestion("How many letter tiles are in a standard English-language Scrabble set?", 100, "", "Hasbro / Wikipedia: Scrabble letter distributions (100 tiles = 98 letters + 2 blanks); verified via Wikipedia"),
    NumericQuestion("How many spaces are on a standard Monopoly board?", 40, "", "Wikipedia: Monopoly (game) — 40 spaces; verified via Wikipedia and HowStuffWorks"),
    NumericQuestion("How many strings does a standard modern concert pedal harp have?", 47, "", "Wikipedia: Pedal harp (47 strings, 7 pedals); verified via Wikipedia and manufacturer string charts (Lyon & Healy, Salvi)"),
    NumericQuestion("How many Platonic solids are there?", 5, "", "Wolfram MathWorld / Wikipedia: Platonic solid (exactly five); verified mathematically"),
    NumericQuestion("How many edges does a cube have?", 12, "", "Wikipedia: Cube (12 edges, 8 vertices, 6 faces); verified mathematically"),
    NumericQuestion("How many prime numbers are there below 100?", 25, "", "List of primes 2..97 contains 25 primes; verified by direct enumeration"),
    NumericQuestion("What is the smallest number expressible as the sum of two positive cubes in two different ways?", 1729, "", "Wolfram MathWorld: Hardy-Ramanujan number; 1729 = 1^3+12^3 = 9^3+10^3; verified by computation"),
    NumericQuestion("What is the measure of each interior angle of a regular pentagon, in degrees?", 108, "degrees", "(5-2)*180/5 = 108; verified by computation"),
    NumericQuestion("What is the sum of all integers from 1 to 100?", 5050, "", "100*101/2 = 5050 (Gauss summation); verified by computation"),
]


BINARY: list[BinaryQuestion] = [
    BinaryQuestion("The Great Wall of China is visible from space with the naked eye.", False),
    BinaryQuestion("Mount Everest is the highest mountain on Earth above sea level.", True),
    BinaryQuestion("Sharks are mammals.", False),
    BinaryQuestion("The Pacific is the largest ocean on Earth.", True),
    BinaryQuestion("Antarctica is the largest desert on Earth.", True),
    BinaryQuestion("Humans and non-avian dinosaurs lived at the same time.", False),
    BinaryQuestion("An octopus has three hearts.", True),
    BinaryQuestion("Humans only use 10% of their brains.", False),
    BinaryQuestion("Venus is the hottest planet in the Solar System.", True),
    BinaryQuestion("Sound travels faster in water than in air.", True),
    BinaryQuestion("Glass at room temperature is a slow-flowing liquid.", False),
    BinaryQuestion("Bats are blind.", False),
    BinaryQuestion("Gold is denser than lead.", True),
    BinaryQuestion("Mercury is the closest planet to the Sun.", True),
    BinaryQuestion("Diamonds are made of carbon.", True),
    BinaryQuestion("The Mona Lisa was painted by Leonardo da Vinci.", True),
    BinaryQuestion("Saturn is the only planet in the Solar System with rings.", False),
    BinaryQuestion("Perfectly pure water is a good conductor of electricity.", False),
    BinaryQuestion("The 'tongue map' of distinct taste zones is a myth.", True),
    BinaryQuestion("Mount Kilimanjaro is the highest mountain in Africa.", True),
    BinaryQuestion("Penguins live naturally in the Arctic.", False),
    BinaryQuestion("Tomatoes are botanically a fruit.", True),
    BinaryQuestion("A year is a leap year every four years with no exceptions.", False),
    BinaryQuestion("The Sahara is larger than the contiguous United States.", True),
    BinaryQuestion("Lightning never strikes the same place twice.", False),
    BinaryQuestion("The human heart is located entirely on the left side of the chest.", False),
    BinaryQuestion("Goldfish have a memory of only a few seconds.", False),
    BinaryQuestion("The Dead Sea's shore is the lowest exposed land on Earth.", True),
    BinaryQuestion("The Great Barrier Reef is the world's largest living structure.", True),
    BinaryQuestion("Light travels faster than sound.", True),
    BinaryQuestion("Chameleons change colour mainly to camouflage themselves.", False),
    BinaryQuestion("Bananas grow on a plant that is botanically a herb, not a tree.", True),
    BinaryQuestion("Water expands when it freezes.", True),
    BinaryQuestion("The adult human has more than 300 bones.", False),
    BinaryQuestion("Neptune is the farthest recognised planet from the Sun.", True),
    BinaryQuestion("The Amazon River discharges more water than any other river in the world.", True, "Wikipedia: Amazon River (avg ~209,000-230,000 m3/s, largest by discharge, ~5x the Congo); verified 2026-07"),
    BinaryQuestion("Canberra is the capital of Australia.", True, "Wikipedia: History of Canberra / NFSA (federal capital, named 1913, Parliament moved 1927); verified 2026-07"),
    BinaryQuestion("The Hundred Years' War lasted more than 100 years.", True, "Wikipedia/Britannica: Hundred Years' War (1337-1453, 116 years); verified 2026-07"),
    BinaryQuestion("Africa is larger in area than North America.", True, "Britannica/Visual Capitalist (Africa ~30.3M km2 vs North America ~24.2M km2); verified 2026-07"),
    BinaryQuestion("Brazil shares a land border with every South American country except Chile and Ecuador.", True, "Wikipedia: Borders of Brazil (borders 9 countries plus French Guiana; only Chile and Ecuador excluded); verified 2026-07"),
    BinaryQuestion("Lake Baikal is the deepest lake in the world.", True, "Britannica/UNESCO/Wikipedia: Lake Baikal (max depth 1,642 m, deepest in the world); verified 2026-07"),
    BinaryQuestion("Napoleon was defeated at the Battle of Waterloo in 1815.", True, "Britannica: Battle of Waterloo (18 June 1815); verified 2026-07"),
    BinaryQuestion("Mexico City sits at a higher elevation than Denver.", True, "Elevation comparison: Mexico City ~2,240 m (7,350 ft) vs Denver 1,609 m (5,280 ft); verified 2026-07"),
    BinaryQuestion("The Ottoman Empire still existed when World War I began.", True, "Wikipedia/Britannica: Ottoman Empire entered WWI 29 Oct 1914; sultanate abolished 1922; verified 2026-07"),
    BinaryQuestion("Vatican City is the smallest country in the world by area.", True, "Britannica: smallest countries list (Vatican 0.44 km2; Monaco second at ~2.1 km2); verified 2026-07"),
    BinaryQuestion("Norway shares a land border with Russia.", True, "Wikipedia: Norway-Russia border (~195.7-197.7 km land border in Sor-Varanger/Pechengsky); verified 2026-07"),
    BinaryQuestion("The Battle of Hastings took place in 1066.", True, "Wikipedia/Britannica: Battle of Hastings (14 Oct 1066); verified 2026-07"),
    BinaryQuestion("Africa has more countries than Europe.", True, "Worldometer (Africa 54 UN members vs Europe 44; Africa larger under any common count); verified 2026-07"),
    BinaryQuestion("Australia is larger in area than Brazil.", False, "Worldometer/Geoscience Australia (Brazil 8.52M km2, 5th largest; Australia 7.74M km2, 6th); verified 2026-07"),
    BinaryQuestion("Istanbul is the capital of Turkey.", False, "Britannica/Wikipedia: Ankara has been the capital of Turkey since 29 Oct 1923; verified 2026-07"),
    BinaryQuestion("Toronto is the capital of Canada.", False, "Britannica/geographyfieldwork: Ottawa is the capital of Canada; verified 2026-07"),
    BinaryQuestion("The Danube is the longest river in Europe.", False, "Wikipedia: Volga (3,531 km) is Europe's longest river; Danube (~2,850 km) is second; verified 2026-07"),
    BinaryQuestion("Greenland is larger in area than Australia.", False, "WorldAtlas/Britannica: Greenland ~2.17M km2 vs Australia ~7.74M km2 (Australia ~3.5x larger); verified 2026-07"),
    BinaryQuestion("Geneva is the capital of Switzerland.", False, "Wikipedia/swissinfo: Bern is the federal city (de facto capital) since 1848; Geneva is not the capital; verified 2026-07"),
    BinaryQuestion("Rio de Janeiro is the capital of Brazil.", False, "Wikipedia: Brasilia has been the capital of Brazil since 21 April 1960; verified 2026-07"),
    BinaryQuestion("The Panama Canal opened before the Suez Canal.", False, "Wikipedia: Suez Canal opened 17 Nov 1869; Panama Canal opened 15 Aug 1914; verified 2026-07"),
    BinaryQuestion("The United States purchased the Louisiana Territory from Spain.", False, "US State Dept/National Archives: Louisiana Purchase was from France (Napoleon), 1803, $15M; verified 2026-07"),
    BinaryQuestion("Aconcagua, the highest mountain in the Americas, is located in Chile.", False, "Wikipedia/Britannica: Aconcagua (~6,961 m) is in Mendoza Province, Argentina, ~15 km from the Chilean border; verified 2026-07"),
    BinaryQuestion("The equator passes through India.", False, "Wikipedia: Geography of India (India spans ~8N-37N; even Indira Point is ~750 km north of the equator); verified 2026-07"),
    BinaryQuestion("Argentina is larger in area than India.", False, "Wikipedia: countries by area (India ~3.29M km2, 7th; Argentina ~2.78M km2, 8th); verified 2026-07"),
    BinaryQuestion("The blue whale is the largest animal known to have ever lived.", True, "Wikipedia: Blue whale / Largest and heaviest animals"),
    BinaryQuestion("Male seahorses carry the developing young in a brood pouch until birth.", True, "Britannica: Do Male Seahorses Give Birth?"),
    BinaryQuestion("Bats are the only mammals capable of true sustained flight.", True, "Wikipedia: Bat"),
    BinaryQuestion("Butterflies can taste with their feet.", True, "Carleton University Dept. of Biology"),
    BinaryQuestion("Helium is lighter than air.", True, "CK-12: Is helium lighter than air?"),
    BinaryQuestion("A proton carries a positive electric charge.", True, "Wikipedia: Proton"),
    BinaryQuestion("Mercury is the only metal that is liquid at ordinary room temperature.", True, "USGS / Wikipedia: mercury only elemental metal liquid at ordinary room temperature; gallium and cesium melt just above"),
    BinaryQuestion("Jupiter is the largest planet in the Solar System.", True, "NASA: Jupiter Facts"),
    BinaryQuestion("A day on Venus is longer than a year on Venus.", True, "Harvard CfA / Space.com: Venus rotation 243 days vs orbit 225 days"),
    BinaryQuestion("The femur is the longest bone in the human body.", True, "Wikipedia: Femur"),
    BinaryQuestion("Hydrogen is the most abundant element in the universe.", True, "US EIA: Hydrogen explained"),
    BinaryQuestion("Spiders are insects.", False, "Burke Museum: Myth - Spiders are insects (they are arachnids)"),
    BinaryQuestion("Dolphins are a type of fish.", False, "NOAA: Are dolphins fish? (they are mammals)"),
    BinaryQuestion("Camels store water in their humps.", False, "Britannica / Library of Congress: humps store fat, not water"),
    BinaryQuestion("Owls can rotate their heads a full 360 degrees.", False, "National Geographic: owls rotate ~270 degrees, not 360"),
    BinaryQuestion("Absolute zero is equal to 0 degrees Celsius.", False, "Wikipedia: Absolute zero is -273.15 C"),
    BinaryQuestion("Oxygen is the most abundant gas in Earth's atmosphere.", False, "Wikipedia: Atmosphere of Earth (nitrogen ~78%, most abundant)"),
    BinaryQuestion("Rubber is a good conductor of electricity.", False, "HM Royal / industry sources: rubber is an electrical insulator"),
    BinaryQuestion("A light-year is a unit of time.", False, "Wikipedia: Light-year (unit of distance, ~9.46 trillion km)"),
    BinaryQuestion("The Sun is classified as a planet.", False, "NASA: the Sun is a star, not a planet"),
    BinaryQuestion("The Sun is the largest known star in the universe.", False, "Star-Facts / Wikipedia: Stephenson 2-18 far larger; Sun is average-sized"),
    BinaryQuestion("Human fingernails continue to grow for several days after a person dies.", False, "Snopes / UAMS Health: myth caused by skin retraction"),
    BinaryQuestion("Pluto is currently classified as a full planet (as of 2024).", False, "NASA / IAU: Pluto reclassified as a dwarf planet in 2006"),
    BinaryQuestion("The human liver is located mainly on the left side of the abdomen.", False, "Johns Hopkins Medicine: liver is in the upper right of the abdomen"),
    BinaryQuestion("George Orwell wrote the novel 'Brave New World'.", False, "Wikipedia/Britannica: Brave New World by Aldous Huxley, published 1932"),
    BinaryQuestion("The Beatles' first studio album was 'Abbey Road'.", False, "Wikipedia/Beatles Bible: debut album was Please Please Me, released 22 Mar 1963"),
    BinaryQuestion("The word 'robot' comes from a Czech word meaning forced labour.", True, "Merriam-Webster/MIT Press: Czech 'robota' (forced labor), coined for Capek's R.U.R."),
    BinaryQuestion("Rudyard Kipling won the first Nobel Prize in Literature in 1901.", False, "NobelPrize.org: 1901 laureate was Sully Prudhomme; Kipling won in 1907"),
    BinaryQuestion("The QWERTY keyboard layout was designed in the 19th century.", True, "Smithsonian/Wikipedia: Christopher Latham Sholes, 1870s (patented 1878)"),
    BinaryQuestion("Usain Bolt's men's 100 m world record stands at 9.58 seconds (as of 2024).", True, "World Athletics: 9.58 set in Berlin 2009; record still standing through 2024"),
    BinaryQuestion("The word 'quarantine' derives from an Italian word meaning forty days.", True, "Etymonline/McGill OSS/Wikipedia: Venetian 'quarantena', from 'quaranta giorni' (forty days)"),
    BinaryQuestion("Vincent van Gogh sold hundreds of paintings during his lifetime.", False, "Van Gogh Museum FAQ/Artnet: at most a handful of sales; only one known public sale (The Red Vineyard)"),
    BinaryQuestion("The first video uploaded to YouTube was titled 'Me at the zoo'.", True, "Wikipedia/Smithsonian: 'Me at the zoo' by Jawed Karim, uploaded 23 Apr 2005"),
    BinaryQuestion("Wimbledon is the oldest of tennis's four Grand Slam tournaments.", True, "Wikipedia/ITF: Wimbledon est. 1877; US 1881, French 1891, Australian 1905"),
    BinaryQuestion("The programming language Python is named after the snake.", False, "Python history/Codecademy: Guido van Rossum named it after Monty Python's Flying Circus"),
    BinaryQuestion("The first modern Olympic marathon, in 1896, was won by a Greek runner.", True, "Wikipedia/Britannica/Olympics.com: Spyridon Louis of Greece, 10 Apr 1896"),
    BinaryQuestion("Beethoven composed the opera 'The Magic Flute'.", False, "Wikipedia/Britannica: The Magic Flute composed by Mozart, premiered 1791"),
    BinaryQuestion("The word 'alphabet' derives from the names of the first two letters of the Greek alphabet.", True, "Britannica/Wikipedia: from Greek alpha + beta, via Latin 'alphabetum'"),
    BinaryQuestion("Michael Phelps has won more Olympic gold medals than any other athlete (as of 2024).", True, "Olympics.com/Wikipedia: Phelps holds record 23 golds; no other athlete has more than 9"),
    BinaryQuestion("The first email over a computer network was sent in the 1980s.", False, "Wikipedia/Internet Hall of Fame: Ray Tomlinson sent first network email on ARPANET in 1971"),
    BinaryQuestion("'The Persistence of Memory', the melting-clocks painting, was painted by Pablo Picasso.", False, "MoMA/Wikipedia: painted by Salvador Dali, 1931"),
    BinaryQuestion("The Tour de France was first held in the 1920s.", False, "Wikipedia/History Today: first Tour de France held in July 1903"),
    BinaryQuestion("Shakespeare's 'Romeo and Juliet' is set in Venice.", False, "SparkNotes/play text: set 'in fair Verona'"),
    BinaryQuestion("Apple was founded before Microsoft.", False, "HISTORY/Library of Congress: Microsoft founded 4 Apr 1975; Apple founded 1 Apr 1976"),
    BinaryQuestion("The first FIFA World Cup, in 1930, was held in Brazil.", False, "Wikipedia/FIFA: 1930 World Cup hosted by Uruguay (all matches in Montevideo)"),
    BinaryQuestion("The Boston Marathon is the world's oldest annual marathon.", True, "Britannica/Wikipedia: held annually since 1897, world's oldest annual marathon"),
    BinaryQuestion("Bluetooth technology is named after a medieval Scandinavian king.", True, "Bluetooth.com/Wikipedia: named after 10th-century Danish king Harald Bluetooth Gormsson"),
    BinaryQuestion("Bob Dylan has won the Nobel Prize in Literature.", True, "NobelPrize.org: awarded the 2016 Nobel Prize in Literature"),
    BinaryQuestion("The word 'denim' derives from the name of the French city of Nimes.", True, "Merriam-Webster/Wikipedia: from 'serge de Nimes', fabric of Nimes, France"),
]


def counts() -> tuple[int, int]:
    """Return (numeric, binary) question counts. Handy for the CLI banner."""
    return len(NUMERIC), len(BINARY)
